# Generated by Django 5.1 on 2024-08-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 22, 6, 40, 23, 838387, tzinfo=datetime.timezone.utc)),
        ),
    ]
