# Generated by Django 5.1 on 2024-08-22 07:59

import backendapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_weather_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.TimeField(default=backendapp.models.current_time),
        ),
    ]
